print('Esta es una prueba para el laboratorio control git')
print('Ejercicio para la creación de un nuevo archivo')
print('Simulacro de cambios: ejercicio de conflictos')
print('Ejercicio para la creaciÃ³n de un nuevo archivo')
print('Prueba de conflictos')
